<?php

global $mod;
global $dbhost;
global $dbuname;
global $dbpass;
global $dbname;
global $table_prefix;

//  MySQL host name, user name, password, database, and table to edit
$opts["hn"] = $dbhost;
$opts["un"] = $dbuname;
$opts["pw"] = $dbpass;
$opts["db"] = $dbname;
$opts["tb"] = $table_prefix . 'modules';

// Name of field which is the unique key
$opts["key"] = "id";

// Type of key field (int/real/string/date etc)
$opts["key_type"] = "int";
// Initial field to sort on
$opts["sort_field"] = "id";

// Number of records to display on the screen
// Note value of -1 lists all records in a table.
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'CV';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Number of lines to display on multiple selection filters
//$opts['default_sort_columns'] = array('pushId','due','priority','task');
$opts['default_sort_columns'] = array();

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'query' => false,
	'sort'  => false,
	'time'  => false
	);

// URLs - You can redefine URL for images to store images on different location
// that phpMyEdit class file.
$opts['url'] = array(
		'images' => './mod/cb_common/phpMyEdit/images/'
		);

// E-mail notification, replace boolean false with e-mail address, ex:
// admin@example.com
$opt['notify'] = array(
	'delete' => false,
	'insert' => false,
	'update' => false
		);

/*
	Field definitions. Fields will be displayed left to right
	on the screen in the order in which they appear in this list.
	['name'] is the title used for column headings, etc.;
	['sort'] = true means the users may sort the display on this column;
	['type'] is generated by SETUP.php and indicates the mysql field type
		best not edited
	['maxlen'] maximum length to display add/edit/search input boxes
	['trimlen'] maximum length of string content to display in row listing
		if strlen(value) > trimlen, display substr(,0,trimlen-3).'...'
	['strip_tags'] true or false. whether to strip tags from content
	['width'] is an optional display width specification for the column,
		e.g.  ['width'] = '100px';
		or $fdd['colname']['width'] = ($fdd['colname']['trimlen'] * 8).'px';
	['nowrap'] true or false.  whether this field should get a NOWRAP
	['mask'] a string that is used by sprintf() to format field output
	['datemask'] a string that is used by date() to format date fields
		see PHP's date() for valid formatting characters
	['daterange'] a  of numbers
		['daterange']['start'] = 1996;
		['daterange']['end']   = $fdd['colname']['daterange']['start']+20;
	['URL'] is used to make a field 'clickable' in the display, e.g.:
		['URL'] = 'mailto:$value' or ['URL'] = 'http://$value';
		['URL'] = '$page?stuff';
		Note that the following are available as variables:
			$key    key field for record
			$name   name of the field
			$value  value of the field
			$page   this HTML page
			$urlstr all page variables
			$row    mysql_fetch_assoc() for this row
		['URLtarget']  HTML target link specification (for example: _blank)
		['URLdisp']    what to display as hypertext link (by default $value)
		['URLprefix']  old 3.5 ['URL'] behaviour, will prepend string before
		['URLpostfix'] similary to ['URLprefix'] will append string after
	['required'] = true will generate javascript to prevent null entries by users
	['options'] is an optional parameter to control whether a field is displayed
		L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
		Another flags can be:
		R - indicates that a field is read only
		W - indicates that a field is a password field
		H - indicates that a field is to be hidden and marked as hidden
	['textarea']['rows'] and/or ['textarea']['cols'] specifies a
	textarea is to be used to give multi-line input,
		e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
	['values'] restricts user input to the specified constants,
		e.g. ['values'] = array('A','B','C')
		or   ['values'] = range(1,99);
	['values2'] gives alternative description to ['values'] values
		e.g.	['values'] = array('A','B','C')
				['values2'] = array('Apple', 'Bradley' , 'Chuck')
	['values']['table'] and ['values']['column'] restricts user
		input to the values found in the specified column of another table.
 		The optional ['values']['description'] field allows the value(s) displayed
 		to the user to be different to those in the ['values']['column'] field.
 		This is useful for giving more meaning to column values.  There are two main
 		options when using the ['values']['description'] field. These are whether you
 		want to use a single, or multiple field in your description.  To apply single,
 		you need to use:
 			['values']['description'] = 'desc_column'
 		This may be used, with no other options, and will simply display the description
 		for the corresponding value.
 		For Multiple, use:
 			['values']['description']['columns']['1'] = 'desc_column_1'
 			['values']['description']['divs']['1']    = ' '
 			['values']['description']['columns']['2'] = 'desc_column_2'
 		The 'div' component is what will be used as a divider between the columns
 		in the display.  You don't need to define the last 'div' field if it isn't
 		required.  So, for example...if you have a series of people in a
 		table, with a separate column for id, first name, and last name, you could
 		use:
			['values']['db']='mydb' *optional if table is in another database*
			['values']['table']='mytable'
 			['values']['column']='id'
 			['values']['description']['columns']['1']='name_last'
 			['values']['description']['divs']['1']   =', '
 			['values']['description']['columns']['2']='name_first'
			['values']['filters']='idcolumn in (1,2,3)' *optional WHERE clause*
 			['values']['orderby']='last_name' *optional ORDER BY clause*
		if a column is either SET or ENUM type, then the values are put in 
		by PME Setup.
	['select'] = 'T/D/M' (text, drop-down, or multiple selection for filters)
		if a column is a SET type, then this is automatically 'M'
	Calculated Expressions
		example:
			$fdd['other']['name']='Col Header';
			$fdd['other']['expression']='onHand-ordered';
			$fdd['other']['sort']='T:!';
			$fdd['other']['select']='T';
			$fdd['other']['type']='int';
		'other' can be anything, but needs to be unique within the list of $fdd keys
		'expression' can be any valid MySQL expression
		'type' should reflect the results of the expression, e.g. 'int' or 'string'
		all other options work as with other, normal columns
		this kind of column is always read-only
	Special note:
		Note, that you can create special options for particular $fdd array
		elements, that depends on performed action. In example if you can
		change name of column in list and filter action, you can define
		$fdd['column']['name|FL']. Others options works of course also well.
*/
$opts['fdd']['id'] = array(
	'name'=>'ID',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'int',
	'maxlen'=>4,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['name'] = array(
	'name'=>'Displayed Name',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>100,
	'nowrap'=>false,
	'required'=>true,
	'options'=>null,
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['source_file'] = array(
	'name'=>'Source file',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>60,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['img'] = array(
	'name'=>'Img',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>25,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['plug_dir'] = array(
	'name'=>'Plug dir',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>100,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['block_pos'] = array(
	'name'=>'Display Position',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'int',
	'maxlen'=>2,
	'nowrap'=>false,
	'required'=>true,
	'options'=>null,
	'values'=>array( 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
		17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 ),
	'values2' => array(
		'Off',
		'Left',
		'Top Center',
		'Right',
		'Middle Center',
		'Bottom Center',
		'Left & Top Center',
		'Left & Middle Center',
		'Left & Bottom Center',
		'Left & Right',
		'Top Center & Middle Center',
		'Top Center & Bottom Center',
		'Top Center and Right', 
		'Middle Center & Bottom Center',
		'Middle Center & Right',
		'Bottom Center & Right',
		'Left, Top Center & Right',
		'Left, Middle Center & Right',
		'Left, Bottom Center & Right',
		'Top Center, Middle Center & Right',
		'Top Center, Bottom Center & Right',
		'Middle Center, Bottom Center & Right',
		'Top Center, Middle Center & Left',
		'Top Center, Bottom Center & Left',
		'Middle Center, Bottom Center & Left',
		'Top Center, Middle Center & Bottom Center',
		'Top Center, Middle Center, Left & Right',
		'Top Center, Bottom Center, Left & Right',
		'Middle Center, Bottom Center, Left & Right',
		'Top Center, Middle Center, Bottom Center & Right',
		'Top Center, Middle Center, Bottom Center & Left',
		'All'
	),
	'default'=>'0',
	'sort'=>true
);

$opts['fdd']['block_file'] = array(
	'name'=>'Block file',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>20,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['admin_only'] = array(
	'name'=>'Admin View Only',
	'values'=>array( 0, 1 ),
	'values2'=>array( 'No', 'Yes' ),
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'int',
	'maxlen'=>1,
	'nowrap'=>false,
	'required'=>true,
	'options'=>null,
	'default'=>'0',
	'sort'=>true
);

$opts['fdd']['user_only'] = array(
	'name'=>'User View Only',
	'values'=>array( 0, 1 ),
	'values2'=>array( 'No', 'Yes' ),
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'int',
	'maxlen'=>1,
	'nowrap'=>false,
	'required'=>true,
	'options'=>null,
	'default'=>'0',
	'sort'=>true
);

$opts['fdd']['admin_inc'] = array(
	'name'=>'Admin inc',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'string',
	'maxlen'=>20,
	'nowrap'=>false,
	'required'=>true,
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['fdd']['about'] = array(
	'name'=>'About',
	'help'=>'',
	'strip_tags'=>false,
	'select'=>'T',
	'type'=>'blob',
	'maxlen'=>16777215,
	'nowrap'=>false,
	'required'=>true,
	'textarea'=>array(
		'rows'=>5,
		'cols'=>50,
		'wrap'=>'virtual'
	),
	'options'=>'H',
	'values'=>null,
	'values2'=>null,
	'default'=>'',
	'sort'=>true
);

$opts['filters'] = "plug_dir = '$mod'";

/* Table-level filter capability (if set, is included in the WHERE clause of any
   generated SELECT statement; this gives you ability to wirk only with subset of
   data from table)

   Some valid examples:
     $opts['filters'] = "column1 like '%11%' AND column2<17";
     $opts['filters'] = "section_id = 9";
     $opts['filters'] = "Table0.sessions_count > 200";
 */

/* CGI variables. You can optionally append or overwrite particular variables
   returned from CGI environment (GET/POST HTTP protocol data). Use these two
   arrays for this purpose, where array key mean CGI variable name and value
   means CGI variable value.

   Examples:
     // This will cause descending sorting according first field if other
	 // type of sort was not specified/selected by user.
     $opts['cgi']['append']    = array('sfn' => '-0');
	 // This will cause the same sort allways in all cases.
     $opts['cgi']['overwrite'] = array('sfn' => '-0');
 */

/*
Triggers are files that are included (via require) that perform
actions (before or after) X (inserts, updates, or deletes).

'before' triggers are usually used to verify conditions prior to
executing the main operation.

'after' triggers are usually used to perform follow-on operations
after the main operation.  For example, to update secondary tables
to enforce referential integrity or to update aggregate tables.

The operation sequence is this:  before, main, after.  If any
operation fails, not only should the next operation(s) not be
executed, but the previous ones are 'rolled back' as if they
never happened.  If a database is not able to do this, it is
not 'transaction-safe'.

Triggers are risky in basic MySQL as there is no native transaction
support--it is not transaction-safe by default.  There are
transaction-safe table types in MySQL that can be conditionally built
(see MySQL-Max), but phpMyEdit is currently not set up to support real
transactions.  What that means is that if an operation fails, the
database may be left in an intermediate and invalid state. 

The programmer must understand and accept these risks prior to using
the phpMyEdit triggers mechanism.

If the triggers are used, they execute within the namespace or scope
of the phpMyEdit class.

They _must_ return true or false to indicate success or failure.
*/

/*
$opts['triggers']['insert']['before']='phpws_modules.TIB.inc';
$opts['triggers']['insert']['after'] ='phpws_modules.TIA.inc';
$opts['triggers']['update']['before']='phpws_modules.TUB.inc';
$opts['triggers']['update']['after'] ='phpws_modules.TUA.inc';
$opts['triggers']['delete']['before']='phpws_modules.TDB.inc';
$opts['triggers']['delete']['after'] ='phpws_modules.TDA.inc';
*/

/* Logtable schema

CREATE TABLE changelog (
  updated timestamp(14) NOT NULL,
  user varchar(50) default NULL,
  host varchar(255) NOT NULL default '',
  operation varchar(50) default NULL,
  tab varchar(50) default NULL,
  rowkey varchar(255) default NULL,
  col varchar(255) default NULL,
  oldval blob,
  newval blob
);

$opts['logtable']= 'changelog';
*/


/* Get the user's default language and use it if possible or you can specify
   language particular one you want to use. Available languages are:
   DE EN-US EN FR IT NL PG SK SP */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'];

/* Code execution. Since version 4.0 phpMyEdit will automatically starts its
   execution. You can turn this feature off by setting $opts['execute'] to 0.
   Default value is 1. */

//  and now the all-important call to phpMyEdit
//  warning - beware of case-sensitive operating systems!
// require_once 'phpMyEdit.class.php';

$MyForm = new phpMyEdit($opts);

?>
