<?php

/*
 * phpMyEdit language file
 *
 * language: dutch (standard)
 * encoding: iso-8859-1
 * date: 21/09/2002
 * authors:
 *   Paul Barends <pbarends@xs4all.nl>
 *   Erwin Janszen <Erwin.Janszen@mail.ing.nl>
 */

/* $Platon: phpMyEdit/lang/PME.lang.NL.inc,v 1.5 2002/11/07 12:36:59 nepto Exp $ */

return Array(
		'Prev'              =>'Vorige',
		'Add'               =>'Toevoegen',
		'Copy'              =>'Copiëren',
		'Change'            =>'Bewerken',
		'Delete'            =>'Wissen',
		'View'              =>'Details',
		'Next'              =>'Volgende',
		'Page'              =>'Pagina',
		'Records'           =>'Rijen',
		'Save'              =>'Bewaren',
		'More'              =>'Meer',
		'Cancel'            =>'Annuleren',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'of'                =>'van',
		'record added'      =>'Rij toegevoegd',
		'record changed'    =>'Rij aangepast',
		'record deleted'    =>'Rij gewist',
		'Please enter'      =>'Voer a.u.b. in:',
		'months' => Array(
			'01'=>'januari',
			'02'=>'februari',
			'03'=>'maart',
			'04'=>'april',
			'05'=>'mei',
			'06'=>'juni',
			'07'=>'juli',
			'08'=>'augustus',
			'09'=>'september',
			'10'=>'october',
			'11'=>'november',
			'12'=>'december')
		);

?>
