<?php

/*
 * phpMyEdit language file
 *
 * language: polish
 * encoding: iso-8859-2
 * date: 01/10/2002
 * author: Piotr Walesiuk <piotrw@uwb.edu.pl>
 */

/* $Platon: phpMyEdit/lang/PME.lang.PL.inc,v 1.3 2002/10/23 19:08:15 nepto Exp $ */

return Array(
		'Encoding'      =>'iso-8859-2',
		'Prev'         	=>'Wstecz',
		'Add'          	=>'Dodaj',
		'Copy'         	=>'Kopiuj',
		'Change'       	=>'Zmieñ',
		'Delete'       	=>'Usuñ',
		'View'      	=>'Poka¿',
		'Next'         	=>'Dalej',
		'Page'         	=>'Strona',
		'Records'      	=>'Rekordy',
		'Save'          =>'Zapisz',
		'More'          =>'Wiêcej',
		'Cancel'        =>'Anuluj',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'of'            =>'z',
		'record added'  =>'rekord dodany',
		'record changed'=>'rekord zmieniony',
		'record deleted'=>'rekord usuniêty',
		'Please enter'  =>'Proszê wprowadziæ',
		'months'	=> Array(
			'01'=>'Styczeñ',
			'02'=>'Luty',
			'03'=>'Marzec',
			'04'=>'Kwiecieñ',
			'05'=>'Maj',
			'06'=>'Czerwiec',
			'07'=>'Lipiec',
			'08'=>'Sierpieñ',
			'09'=>'Wrzesieñ',
			'10'=>'Pa¼dziernik',
			'11'=>'Listopad',
			'12'=>'Grudzieñ')
		);

?>
