<?php

/*
 * phpMyEdit language file
 *
 * language: english (United States)
 * encoding: iso-8859-1
 * date: 02/2002
 * author: Jim Kraai <jkraai@users.sourceforge.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.EN-US.inc,v 1.5 2002/10/23 19:08:14 nepto Exp $ */

return Array(
		'Prev'          	=>'Prev',
		'Add'           	=>'Add',
		'Copy'           	=>'Copy',
		'Change'        	=>'Change',
		'Delete'        	=>'Delete',
		'View'	     	 	=>'View',
		'Next'          	=>'Next',
		'Page'          	=>'Page',
		'Records'       	=>'Records',
		'Save'          	=>'Save',
		'More'          	=>'More',
		'Cancel'        	=>'Cancel',
		'Search'			=>'Search',
		'Hide'				=>'Hide',
		'Clear'				=>'Clear',
		'Query'				=>'Query',
		'of'				=>'of',
		'record added'  	=>'record added',
		'record changed'	=>'record changed',
		'record deleted'	=>'record deleted',
		'Please enter'  	=>'Please enter',
		'months' => Array(
			'01'=>'January',
			'02'=>'February',
			'03'=>'March',
			'04'=>'April',
			'05'=>'May',
			'06'=>'June',
			'07'=>'July',
			'08'=>'August',
			'09'=>'September',
			'10'=>'October',
			'11'=>'November',
			'12'=>'December')
		);

?>
