<?php

/*
 * phpMyEdit language file
 *
 * language: slovak
 * encoding: iso-8859-2
 * date: 02/02/2002
 * author: Ondrej Jombik <nepto@php.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.SK.inc,v 1.7 2002/10/23 19:08:15 nepto Exp $ */

return Array(
		'Encoding'      =>'iso-8859-2',
		'Prev'         	=>'Predchádzajúci',
		'Add'          	=>'Prida»',
		'Copy'         	=>'Kopírova»',
		'Change'       	=>'Zmeni»',
		'Delete'       	=>'Zmaza»',
		'View'      	=>'Pozrie»',
		'Next'         	=>'Ïal¹í',
		'Page'         	=>'Stránka',
		'Records'      	=>'Záznamov',
		'Save'          =>'Ulo¾i»',
		'More'          =>'Viac',
		'Cancel'        =>'Storno',
		'Search'		=>'Hµada»',
		'Hide'			=>'Skry»',
		'Clear'			=>'Zru¹i»',
		'Query'			=>'Vyhµada»',
		'of'			=>'z',
		'record added'  =>'záznam pridaný',
		'record changed'=>'záznam zmenený',
		'record deleted'=>'záznam zmazaný',
		'Please enter'  =>'Prosím zadajte',
		'months'	=> Array(
			'01'=>'Január',
			'02'=>'Február',
			'03'=>'Marec',
			'04'=>'Apríl',
			'05'=>'Máj',
			'06'=>'Jún',
			'07'=>'Júl',
			'08'=>'August',
			'09'=>'September',
			'10'=>'Október',
			'11'=>'November',
			'12'=>'December')
		);

?>
