<?php

/*
 * phpMyEdit language file
 *
 * language: french (standard) 
 * encoding: iso-8859-1
 * date: 02/2002, 7/11/2002
 * author: Dario <dartar@users.sourceforge.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.FR.inc,v 1.6 2002/11/07 12:57:22 nepto Exp $ */

return Array(
		'Prev'          =>'Précédent',
		'Add'           =>'Ajouter',
		'Copy'          =>'Copier',
		'Change'        =>'Changer',
		'Delete'        =>'Effacer',
		'View'      	=>'Afficher',
		'Next'          =>'Suivant',
		'Page'          =>'Page',
		'Records'       =>'Records',
		'Save'          =>'Enregistrer',
		'More'          =>'Enregistrer et continuer',
		'Cancel'        =>'Annuler',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'of'		    =>'/', // untranslated
		'record added'  =>'record a été ajouté',
		'record changed'=>'record a été changé',
		'record deleted'=>'record a été effacé',
		'Please enter'  =>'Entrez s\'il vous plaît',
		'months'	=> Array(
			'01'=>'Janvier',
			'02'=>'Février',
			'03'=>'Mars',
			'04'=>'Avril',
			'05'=>'Mai',
			'06'=>'Juin',
			'07'=>'Juillet',
			'08'=>'Août',
			'09'=>'Septembre',
			'10'=>'Octobre',
			'11'=>'Novembre',
			'12'=>'Décembre')
		);

?>
