<?php

/*
 * phpMyEdit language file
 *
 * language: italian (standard)
 * encoding: iso-8859-1
 * date: 02/2002, 7/11/2002
 * author: Dario <dartar@users.sourceforge.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.IT.inc,v 1.6 2002/11/07 12:46:56 nepto Exp $ */

return Array(
		'Prev'          =>'Precedente',
		'Add'           =>'Aggiungi',
		'Copy'          =>'Copia',
		'Change'        =>'Modifica',
		'Delete'        =>'Cancella',
		'View'      	=>'Visualizza',
		'Next'          =>'Seguente',
		'Page'          =>'Pagina',
		'Records'       =>'Voci',
		'Save'          =>'Salva',
		'More'          =>'Salva & Continua',
		'Cancel'        =>'Annulla',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'of'            =>'/', // untranslated
		'record added'  =>'voce aggiunta',
		'record changed'=>'voce modificata',
		'record deleted'=>'voce eliminata',
		'Please enter'  =>'Si prega di riempire il campo: ',
		'months'	=> Array(
			'01'=>'Gennaio',
			'02'=>'Febbraio',
			'03'=>'Marzo',
			'04'=>'Aprile',
			'05'=>'Maggio',
			'06'=>'Giugno',
			'07'=>'Luglio',
			'08'=>'Agosto',
			'09'=>'Settembre',
			'10'=>'Ottobre',
			'11'=>'Novembre',
			'12'=>'Dicembre')
		);

?>
