<?php

/*
 * phpMyEdit language file
 *
 * language: german (standard)
 * encoding: iso-8859-1
 * date: 07/2002
 * author: Christof Brandstetter <fellz@users.sourceforge.net>
 * info: http://sourceforge.net/tracker/index.php?func=detail&aid=524371&group_id=12479&atid=212479
 */

/* $Platon: phpMyEdit/lang/PME.lang.DE.inc,v 1.6 2002/10/23 19:08:14 nepto Exp $ */

return Array(
		'Prev'          =>'Zurueck',
		'Add'           =>'Hinzufuegen',
		'Copy'         	=>'Kopieren',
		'Change'        =>'Aendern',
		'Delete'        =>'Loeschen',
		'View'      	=>'Anzeigen',
		'Next'          =>'Weiter',
		'Page'          =>'Seite',
		'Records'       =>'Datensaetze',
		'Save'          =>'Speichern',
		'More'          =>'Speichern, weiteren Datensatz hinzufuegen',
		'Cancel'        =>'Abbrechen',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'of'			=>'von', // translated correctly?
		'record added'  =>'Datensatz hinzugefuegt',
		'record changed'=>'Datensatz geaendert',
		'record deleted'=>'Datensatz geloescht',
		'Please enter'  =>'Bitte fuellen sie dieses Feld aus:',
		'months' =>	Array(
				'01'=>'Januar',
				'02'=>'Februar',
				'03'=>'März',
				'04'=>'April',
				'05'=>'Mag',
				'06'=>'Juni',
				'07'=>'Juli',
				'08'=>'August',
				'09'=>'September',
				'10'=>'Oktober',
				'11'=>'November',
				'12'=>'Dezember')
		);

?>
